export const alertsData = [
  {
    id: 1,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Your request has been approved",
    notificationType: "Rent",
  },
  {
    id: 2,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Your request has been approved",
    notificationType: "Maintenance",
  },
  {
    id: 3,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Your request has been approved",
    notificationType: "Complains",
  },
  {
    id: 4,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Your payment for December rent has been received.",
    notificationType: "Rent",
  },
  {
    id: 5,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Scheduled maintenance has been completed successfully.",
    notificationType: "Maintenance",
  },
  {
    id: 6,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Your complaint regarding noise disturbance has been addressed.",
    notificationType: "Complains",
  },
  {
    id: 7,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Your request for a rent extension has been granted.",
    notificationType: "Rent",
  },
  {
    id: 8,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "A technician has been dispatched to fix the elevator issue.",
    notificationType: "Maintenance",
  },
  {
    id: 9,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Your complaint regarding a leaky faucet has been resolved.",
    notificationType: "Complains",
  },
  {
    id: 10,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Reminder: Rent payment is due by the end of the week.",
    notificationType: "Rent",
  },
  {
    id: 11,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Scheduled maintenance for the heating system will occur next week.",
    notificationType: "Maintenance",
  },
  {
    id: 12,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Your complaint regarding a broken light fixture has been fixed.",
    notificationType: "Complains",
  },
  {
    id: 13,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Rent increase notice: Please review the updated terms.",
    notificationType: "Rent",
  },
  {
    id: 14,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Scheduled maintenance for the parking lot will occur next week.",
    notificationType: "Maintenance",
  },
  {
    id: 15,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Your complaint regarding a noisy neighbor has been resolved.",
    notificationType: "Complains",
  },
  {
    id: 16,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Reminder: Rent payment is due tomorrow.",
    notificationType: "Rent",
  },
  {
    id: 17,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Scheduled maintenance for the elevator will occur next week.",
    notificationType: "Maintenance",
  },
  {
    id: 18,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Your complaint regarding a broken window has been fixed.",
    notificationType: "Complains",
  },
  {
    id: 19,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText: "Rent payment reminder: Your rent is overdue.",
    notificationType: "Rent",
  },
  {
    id: 20,
    dateAndYear: "12/12/2021",
    time: "12:00",
    name: "John Doe",
    userType: "Manager",
    notificationText:
      "Scheduled maintenance for the HVAC system will occur next week.",
    notificationType: "Maintenance",
  },
];
