export const icons = {
  userIcon: require("../assets/icons/userIcon.png"),
  passwordFieldIcon: require("../assets/icons/passwordFieldIcon.png"),
  calendarIcon: require("../assets/icons/calendar.png"),
  emailIcon: require("../assets/icons/email.png"),
  phoneNumberIcon: require("../assets/icons/phone-number.png"),
  downLongArrow: require("../assets/icons/down-long-arrow.png"),
  upLongArrow: require("../assets/icons/up-long-arrow.png"),
  incomingArrow: require("../assets/icons/incoming-arrow.png"),
  outgoingArrow: require("../assets/icons/outgoing-arrow.png"),
  externalLink: require("../assets/icons/external-link.png"),
  barGraph: require("../assets/icons/bar-graph.png"),
  home: require("../assets/icons/home.png"),
  star: require("../assets/icons/star.png"),
  like: require("../assets/icons/like.png"),
  dislike: require("../assets/icons/dislike.png"),
  hidePasswordIcon: require("../assets/icons/hide-password.png"),
  showPasswordIcon: require("../assets/icons/show-password.png"),
};
