// Description: This file contains the image imports for the app that are used all across it.

export const icons = {
  userIcon: require("../assets/icons/userIcon.png"),
  passwordFieldIcon: require("../assets/icons/passwordFieldIcon.png"),
  calendarIcon: require("../assets/icons/calendar.png"),
  emailIcon: require("../assets/icons/email.png"),
  phoneNumberIcon: require("../assets/icons/phone-number.png"),
  downLongArrow: require("../assets/icons/down-long-arrow.png"),
  upLongArrow: require("../assets/icons/up-long-arrow.png"),
  externalLink: require("../assets/icons/external-link.png"),
  barGraph: require("../assets/icons/bar-graph.png"),
  home: require("../assets/icons/home.png"),
  star: require("../assets/icons/star.png"),
  starHollow: require("../assets/icons/star-hollow.png"),
  like: require("../assets/icons/like.png"),
  dislike: require("../assets/icons/dislike.png"),
  hidePasswordIcon: require("../assets/icons/hide-password.png"),
  showPasswordIcon: require("../assets/icons/show-password.png"),
  collapseArrow: require("../assets/icons/collapse-arrow.png"),
  expandArrow: require("../assets/icons/expand-arrow.png"),
  languageIcon: require("../assets/icons/language.png"),
  analyticsIcon: require("../assets/icons/analytics.png"),
  propertiesIcon: require("../assets/icons/properties.png"),
  alertIcon: require("../assets/icons/alert.png"),
  sunIcon: require("../assets/icons/sun.png"),
  moonIcon: require("../assets/icons/moon.png"),
  crossIcon: require("../assets/icons/disabled.png"),
  checkIcon: require("../assets/icons/check.png"),
  expandArrowButton: require("../assets/icons/external-link-button-arrow.png"),
  // areaIcon: require("../assets/icons/area.png"),
  // heightIcon: require("../assets/icons/height.png"),
  // apartments: require("../assets/icons/apartments.png"),
  // balconyIcon: require("../assets/icons/balcony.png"),
  // bedroomsIcon: require("../assets/icons/bedrooms.png"),
  // floorsIcon: require("../assets/icons/floors.png"),
  // kitchensIcon: require("../assets/icons/kitchens.png"),
  // loungesIcon: require("../assets/icons/lounges.png"),
  // conferenceRoomsIcon: require("../assets/icons/conference-rooms.png"),
  // officesIcon: require("../assets/icons/offices.png"),
  // shopsIcon: require("../assets/icons/shops.png"),
  // storeRoomsIcon: require("../assets/icons/store-rooms.png"),
  // toiletsIcon: require("../assets/icons/toilets.png"),
  // parkingCapacityIcon: require("../assets/icons/parking-capacity.png"),
  // personCapacityIcon: require("../assets/icons/person-capacity.png"),
};
