export const pendingRentsData = [
  {
    id: 1,
    address: "772, Street 14, G-11/1",
    city: "Islamabad",
    manager: "Aisha Malik",
    tenant: "Noor Ahmed",
    rentDue: 15000,
  },
  {
    id: 2,
    address: "123, Street 22, F-8/1",
    city: "Rawalpindi",
    manager: "Fatima Raza",
    tenant: "Ali Abbas",
    rentDue: 25000,
  },
  {
    id: 3,
    address: "456, Street 33, G-10/2",
    city: "Islamabad",
    manager: "Hassan Ahmed",
    tenant: "Muhammad Ali",
    rentDue: 30000,
  },
  {
    id: 4,
    address: "789, Street 44, I-8/4",
    city: "Rawalpindi",
    manager: "Zainab Khan",
    tenant: "Omar Raza",
    rentDue: 20000,
  },
  {
    id: 5,
    address: "772, Street 14, G-11/1",
    city: "Islamabad",
    manager: "Aisha Malik",
    tenant: "Noor Ahmed",
    rentDue: 35000,
  },
  {
    id: 6,
    address: "123, Street 22, F-8/1",
    city: "Rawalpindi",
    manager: "Fatima Raza",
    tenant: "Ali Abbas",
    rentDue: 18000,
  },
  {
    id: 7,
    address: "456, Street 33, G-10/2",
    city: "Islamabad",
    manager: "Hassan Ahmed",
    tenant: "Muhammad Ali",
    rentDue: 42000,
  },
  {
    id: 8,
    address: "789, Street 44, I-8/4",
    city: "Rawalpindi",
    manager: "Zainab Khan",
    tenant: "Omar Raza",
    rentDue: 27000,
  },
  {
    id: 9,
    address: "772, Street 14, G-11/1",
    city: "Islamabad",
    manager: "Aisha Malik",
    tenant: "Noor Ahmed",
    rentDue: 38000,
  },
  {
    id: 10,
    address: "123, Street 22, F-8/1",
    city: "Rawalpindi",
    manager: "Fatima Raza",
    tenant: "Ali Abbas",
    rentDue: 22000,
  },
  {
    id: 11,
    address: "456, Street 33, G-10/2",
    city: "Islamabad",
    manager: "Hassan Ahmed",
    tenant: "Muhammad Ali",
    rentDue: 40000,
  },
  {
    id: 12,
    address: "789, Street 44, I-8/4",
    city: "Rawalpindi",
    manager: "Zainab Khan",
    tenant: "Omar Raza",
    rentDue: 31000,
  },
  {
    id: 13,
    address: "772, Street 14, G-11/1",
    city: "Islamabad",
    manager: "Aisha Malik",
    tenant: "Noor Ahmed",
    rentDue: 27000,
  },
  {
    id: 14,
    address: "123, Street 22, F-8/1",
    city: "Rawalpindi",
    manager: "Fatima Raza",
    tenant: "Ali Abbas",
    rentDue: 48000,
  },
  {
    id: 15,
    address: "456, Street 33, G-10/2",
    city: "Islamabad",
    manager: "Hassan Ahmed",
    tenant: "Muhammad Ali",
    rentDue: 36000,
  },
  {
    id: 16,
    address: "789, Street 44, I-8/4",
    city: "Rawalpindi",
    manager: "Zainab Khan",
    tenant: "Omar Raza",
    rentDue: 29000,
  },
  {
    id: 17,
    address: "772, Street 14, G-11/1",
    city: "Islamabad",
    manager: "Aisha Malik",
    tenant: "Noor Ahmed",
    rentDue: 39000,
  },
  {
    id: 18,
    address: "123, Street 22, F-8/1",
    city: "Rawalpindi",
    manager: "Fatima Raza",
    tenant: "Ali Abbas",
    rentDue: 26000,
  },
  {
    id: 19,
    address: "456, Street 33, G-10/2",
    city: "Islamabad",
    manager: "Hassan Ahmed",
    tenant: "Muhammad Ali",
    rentDue: 43000,
  },
  {
    id: 20,
    address: "789, Street 44, I-8/4",
    city: "Rawalpindi",
    manager: "Zainab Khan",
    tenant: "Omar Raza",
    rentDue: 32000,
  },
];
