export const propertiesData = [
  {
    id: 1,
    address: "325, Street 23, G-10/4",
    city: "Islamabad",
    income: "32000",
    outcome: "16000",
    status: "Vacant",
    rentStatus: "Pending",
  },
  {
    id: 2,
    address: "772, Street 14, G-11/1",
    city: "Islamabad",
    income: "18000",
    outcome: "10000",
    status: "On-Rent",
    manager: "Aisha Malik",
    tenant: "Noor Ahmed",
  },
  {
    id: 3,
    address: "489, Street 45, G-11/1",
    city: "Rawalpindi",
    income: "25000",
    outcome: "12000",
    status: "Vacant",
    manager: "Ibrahim Khan",
  },
  {
    id: 4,
    address: "211, Street 36, G-10/4",
    city: "Islamabad",
    income: "48000",
    outcome: "23000",
    status: "On-Rent",
  },
  {
    id: 5,
    address: "548, Street 8, G-11/1",
    city: "Islamabad",
    income: "41000",
    outcome: "20000",
    status: "Vacant",
    manager: "Ali Ahmed",
  },
  {
    id: 6,
    address: "123, Street 17, G-10/4",
    city: "Rawalpindi",
    income: "30000",
    outcome: "15000",
    status: "On-Rent",
    manager: "Fatima Bibi",
    rentStatus: "Collected",
  },
  {
    id: 7,
    address: "789, Street 32, G-11/1",
    city: "Islamabad",
    income: "35000",
    outcome: "18000",
    status: "Vacant",
    manager: "Omar Siddiqui",
    rentStatus: "Pending",
  },
  {
    id: 8,
    address: "456, Street 19, G-10/4",
    city: "Islamabad",
    income: "22000",
    outcome: "10000",
    status: "On-Rent",
    rentStatus: "Collected",
  },
  {
    id: 9,
    address: "890, Street 27, G-11/1",
    city: "Rawalpindi",
    income: "42000",
    outcome: "21000",
    status: "Vacant",
    manager: "Huda Ali",
  },
  {
    id: 10,
    address: "654, Street 11, G-10/4",
    city: "Islamabad",
    income: "38000",
    outcome: "19000",
    status: "Vacant",
    manager: "Ibrahim Khan",
    rentStatus: "Pending",
  },
  {
    id: 11,
    address: "987, Street 28, G-11/1",
    city: "Islamabad",
    income: "28000",
    outcome: "15000",
    status: "On-Rent",
    rentStatus: "Collected",
  },
  {
    id: 12,
    address: "345, Street 15, G-10/4",
    city: "Islamabad",
    income: "45000",
    outcome: "23000",
    status: "Vacant",
    manager: "Ali Ahmed",
    tenant: "Hamza Khan",
  },
  {
    id: 13,
    address: "741, Street 37, G-11/1",
    city: "Rawalpindi",
    income: "32000",
    outcome: "15000",
    status: "On-Rent",
    manager: "Maryam Siddiqui",
  },
  {
    id: 14,
    address: "876, Street 22, G-10/4",
    city: "Islamabad",
    income: "28000",
    outcome: "12000",
    status: "Vacant",
    manager: "Ahmed Malik",
    rentStatus: "Pending",
  },
  {
    id: 15,
    address: "543, Street 9, G-11/1",
    city: "Islamabad",
    income: "39000",
    outcome: "20000",
    status: "On-Rent",
    tenant: "Fatima Bibi",
    rentStatus: "Collected",
  },
  {
    id: 16,
    address: "321, Street 26, G-10/4",
    city: "Rawalpindi",
    income: "24000",
    outcome: "11000",
    status: "Vacant",
    manager: "Youssef Malik",
    tenant: "Ali Ahmed",
  },
  {
    id: 17,
    address: "654, Street 18, G-11/1",
    city: "Islamabad",
    income: "32000",
    outcome: "16000",
    status: "Vacant",
    manager: "Hassan Ahmed",
    tenant: "Zahra Khan",
    rentStatus: "Pending",
  },
  {
    id: 18,
    address: "789, Street 31, G-10/4",
    city: "Islamabad",
    income: "37000",
    outcome: "18000",
    status: "On-Rent",
    manager: "Noor Ahmed",
    rentStatus: "Collected",
  },
  {
    id: 19,
    address: "210, Street 46, G-11/1",
    city: "Rawalpindi",
    income: "29000",
    outcome: "14000",
    status: "Vacant",
    manager: "Sara Bibi",
    tenant: "Ibrahim Khan",
    rentStatus: "Pending",
  },
  {
    id: 20,
    address: "576, Street 13, G-10/4",
    city: "Islamabad",
    income: "43000",
    outcome: "21000",
    status: "On-Rent",
    manager: "Ahmed Malik",
    tenant: "Amina Khan",
    rentStatus: "Collected",
  },
];
